#Specifies the name of the workflow.
name: CI

#Specifies the actions which the pipeline should run.
on: 
  push:
  pull_request:

#Specifies what should happen when a push or pull request is made to the main branch.
jobs:
  build:

    runs-on: ubuntu-latest

    #Specify that the build should be done with version 16.x of Node.js.
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js and dependencies
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
        
    - name: Run & Build Server
      run: |
        cd server
        npm ci 
        npm run build --if-present
      
    - name: Run & Build UI
      run: |
        cd ui
        npm ci 
        npm run build --if-present
